dist: xenial
language: php
matrix:
  include:
  - php: 7.1
    env: EXECUTE_DEPLOYMENT=true
  - php: 7.2
  - php: 7.3
    env: deps=low UPDATE_TOOLS=true
  fast_finish: true
cache:
  directories:
  - $HOME/.composer/cache
before_install:
- echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc
- phpenv config-rm xdebug.ini || echo "XDebug is not enabled"
- export TOOLBOX_VERSION=$(echo ${TRAVIS_TAG:-"dev"} | sed -e 's/^v//')
- git config user.email 'jakub@zalas.pl' && git config user.name 'Jakub Zalas'
install:
- if [[ $deps = low ]]; then make update-min; else make install; fi
script:
- if [[ $deps = low ]]; then make test-min; else make test; fi
- make package package-devkit test-integration
after_success:
- test "$TRAVIS_PULL_REQUEST" == "false" && test "$EXECUTE_DEPLOYMENT" == "true" && make website publish-website
- test "$TRAVIS_EVENT_TYPE" == "cron" && test "$UPDATE_TOOLS" == "true" && GITHUB_TOKEN=$GH_TOKEN make update-phars
deploy:
  provider: releases
  api_key:
    secure: U0BP6+CaAYKAPC5pNIzgIpITLIL5lc0fPRSRW2SBdCh5u55NuHoHL22LldK+309t0L8mxLybq6yh4pUksBdkKB/gKLEI4Vrc5hZeR1y49kIClDIAllrQeCAn+XgDZlZls/Q/Op8DPkAouJrj0Y2qBTWrhAG1Fhn9SLsIcVG0x4JhbKd4I0IN+G4YgxSpzcdYEc6uszqZrPSGKjK+ygrnZ2IJZ+roUTJIQXCK0KEOGHx7sKS4mtqvd5hEx9P+FUZcs3Pp7nNp/gJBWd80ZNbVj7iiOulc7Fl2BxqLqVKGqyv7ekqyeg2vaDz2GpbBiYGbDXiGQlJ0kGlENCuTyqS0ZQ/j9O0htaO57C1m0HVFu+gX34cnL6vP6dkwqjPRDQA8BQ1YNeKQcCP7LDYY/OXvYwaEhB2iw7/e6PjYhQTv41kStGGyTqrFbGNWpV/JM+7oCjr977C8lfDU9I1A/MHRHQHuMKPLA2jygCIVzibmxElsfDaHkIbrbgKZ4ukRYr9fyDVfjv9L2TNWp19++JdDbwBDutuho9E23AFgqEQJjTGTG4mf9pX3tFlfGv+3VDe7LhNm69Wkat1lMjFnL4qjI+uY2K9JdHqPZPw0SOaUpbh9BSuv7+n3Wp/j59Dva136BOK/KUEleD2PBf2oufO+ETLDEofpKQ8HA0R/8K1HN2w=
  file:
  - build/toolbox.phar
  - build/devkit.phar
  skip_cleanup: true
  on:
    tags: true
    repo: jakzal/toolbox
    condition: "$EXECUTE_DEPLOYMENT"
env:
  global:
    secure: "kIsYjPUzSaCVII5DGE3zNi88fg+L3PMANyMZnrYom+zym5HwAVVzwM/dnsP+XFiqkeuuAqttNolR2D4XyY172F+jfpL3YVEC2P/zGRK2TlHu2TXCqsYx8V/bSPFCmBoWvZrx6qsuocrASaN3EmtZUg4jOnfanYBvEnw+pkLOCzJONaz0xgZVxogpUS+fk2wgXI2vHdHCEZxGcz5YIiyS/v8gWP5iUL6+CADlY9ES+DBSbaz8pP82oSQ8OZmGKRD14dK2dzMksy9MdRyfIHtTvIdo8dqchTjRh6TeXTSc+Xz6LnyQiWJOOBgnVwScILPiYze+ElW5x68fNiyVcbfSuT67fePDEGv8pCO0m0YqctsLrlCuasCx91CgPID3regyXDXeb6Xiz66/+ZzsK0QYCkUzmlkWSHlWASjrDf1703oPQIzXxx5+69ksXLmX+KmPSLsKjsirmfAaCZDPVrsxPxEjUN2Sr6anvL8BWcV36v0h29ingi3dhIBfg4wgJqBG/axiZiK63WfKqwFyFBN7F/lxrdCJZgzVOyCdjDBdcXdTNjESvUC9A3nPJR8keZ3oMlUS4kCVyFpWgB0eBF88TS8aUnWKELXndmGxvQh9NQEW4dj1FjtMHi1ZgLUosixKx7d1MBDBBp9Vg2qYCMbs3g/d6rO8is4aFR8Uc9DjUpY="
addons:
  snaps:
  - name: hub
    classic: true
